services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      MEMORY: "8G"
      DIFFICULTY: "hard"
      OPS: "Ezequiel294"
      VIEW_DISTANCE: "8"
      MAX_PLAYERS: "10"
      ENABLE_WHITELIST: "true"
      FORCE_WHITELIST: "true"
      WHITELIST: |
        Ezequiel294

      TYPE: FABRIC
      FABRIC_LOADER_VERSION: "0.16.12"
      DEBUG: "true"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "beta"
      MODRINTH_PROJECTS: |
        fabric-api
        balm
        lithium
        krypton
        noisium
        chunky
        alternate-current
        scalablelux
        jade
        netherportalfix
        fallingtree
        ct-overhaul-village
        double-doors
        ping-wheel
        additional-structures
        edf-remastered
        ferrite-core
        modernfix
        appleskin
        yungs-api
        jei
        travelersbackpack
        emi
        yungs-better-nether-fortresses
        yungs-better-dungeons
        yungs-better-mineshafts
        yungs-better-ocean-monuments
        yungs-better-strongholds
        yungs-better-jungle-temples
        yungs-better-witch-huts
        yungs-better-end-island
        polymorph
        yungs-better-desert-temples
        yungs-extras
        creeper-overhaul
        nyfs-spiders
        emi-loot
        smarter-farmers-farmers-replant
        farmers-delight-refabricated
        what-are-they-up-to
        hardcore-revival
        monsters-in-the-closet
        adventurez
        jade-addons-fabric
        better-compatibility-checker
        plantsjunk
        jaizmod
        etherology

    volumes:
      - ./data:/data

