services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"
      MEMORY: "4G"
      DIFFICULTY: "hard"
      OPS: "Ezequiel294"
      VIEW_DISTANCE: "12"
      MAX_PLAYERS: "10"
      ENABLE_WHITELIST: "true"
      FORCE_WHITELIST: "true"
      # Add player names to let them join
      WHITELIST: |
        Ezequiel294
      
      TYPE: FORGE
      FORGE_VERSION: "36.2.34"
      DEBUG: "true"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_PROJECTS: |
        xaeros-minimap
        appleskin

      JVM_OPTS: |
        --add-opens java.base/sun.security.util=ALL-UNNAMED
        --add-opens java.base/java.util.jar=ALL-UNNAMED
    volumes:
      - ./data:/data
