services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      MEMORY: "8G"
      DIFFICULTY: "hard"
      OPS: "Ezequiel294"
      VIEW_DISTANCE: "8"
      MAX_PLAYERS: "10"
      ENABLE_WHITELIST: "true"
      FORCE_WHITELIST: "true"
      WHITELIST: |
        Ezequiel294

      TYPE: FABRIC
      FABRIC_INSTALLER_VERSION: 1.0.3
      FABRIC_LOADER_VERSION: 0.16.12
      DEBUG: "true"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "beta"
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        krypton
        noisium
        chunky
        alternate-current
        scalablelux
        jade
        netherportalfix
        fallingtree
        ct-overhaul-village
        double-doors
        ping-wheel
        additional-structures
        edf-remastered

    volumes:
      - ./data:/data
