services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: "1.16.5"
      FORGE_VERSION: "36.2.34"
      MODRINTH_PROJECTS: |
        xaeros-minimap
        appleskin
    volumes:
      - ./data:/data