services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.6"
      MEMORY: "4G"
      DIFFICULTY: "hard"
      OPS: "Ezequiel294"
      VIEW_DISTANCE: "12"
      MAX_PLAYERS: "10"
      ENABLE_WHITELIST: "true"
      FORCE_WHITELIST: "true"
      WHITELIST: |
        Ezequiel294
      
      TYPE: FORGE
      FORGE_VERSION: "50.2.0"
      DEBUG: "true"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "beta"
      MODRINTH_PROJECTS: |
        geophilic
        jei
        terralith
        fallingtree

    volumes:
      - ./data:/data